# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'openweathermap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for openweathermap
	pod 'Alamofire', '~> 5.2'
	pod 'RxSwift', '~> 5'
	pod 'RxCocoa', '~> 5'
  
end
